version: 2
jobs:
  build:
    working_directory: /go/src/github.com/vidsy/backoff
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Revision }}
      - run: BUILD=false /scripts/build.sh
      - save_cache:
          key: dependency-cache-{{ .Revision }}
          paths:
            - vendor
  test:
    working_directory: /go/src/github.com/vidsy/backoff
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Revision }}
      - run: make test
  check_version:
    working_directory: /go/src/github.com/vidsy/backoff
    docker:
      - image: vidsyhq/go-builder:latest
    steps:
      - checkout
      - run: make check-version

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master
      - test:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: master
      - check_version:
          filters:
            branches:
              ignore: master










general:
  branches:
    ignore:
      - master

machine:
  services:
    - docker

dependencies:
  override:
    - make install-test-deps

test:
  override:
    - make check-version
    - make test-ci
